-- MySQL Script generated by MySQL Workbench
-- Wed Dec 12 10:39:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ijemavi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ijemavi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ijemavi` DEFAULT CHARACTER SET utf8 ;
USE `ijemavi` ;

-- -----------------------------------------------------
-- Table `ijemavi`.`obreiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ijemavi`.`obreiros` (
  `id_obreiros` INT NOT NULL AUTO_INCREMENT,
  `nome_obr` VARCHAR(100) NOT NULL,
  `senha_obr` VARCHAR(45) NOT NULL,
  `cpf_obr` VARCHAR(45) NOT NULL,
  `telefone_obr` VARCHAR(45) NOT NULL,
  `sexo_obr` VARCHAR(45) NOT NULL,
  `email_obr` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `datacad_obr` DATE NOT NULL,
  `nascimento_obr` DATE NOT NULL,
  `tipocargo_obr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_obreiros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ijemavi`.`carrouses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ijemavi`.`carrouses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagen_carousel` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `obreiro_carousel_fk` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrouses_obreiros_idx` (`obreiro_carousel_fk` ASC),
  CONSTRAINT `fk_carrouses_obreiros`
    FOREIGN KEY (`obreiro_carousel_fk`)
    REFERENCES `ijemavi`.`obreiros` (`id_obreiros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ijemavi`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ijemavi`.`enderecos` (
  `id_end` INT NOT NULL AUTO_INCREMENT,
  `estado_end` VARCHAR(45) NOT NULL,
  `cidade_end` VARCHAR(45) NULL,
  `bairro_end` VARCHAR(45) NULL,
  `rua_end` VARCHAR(45) NULL,
  `numero_end` VARCHAR(45) NULL,
  `cep_end` VARCHAR(45) NULL,
  `obreiro_end_fk` INT NOT NULL,
  PRIMARY KEY (`id_end`),
  INDEX `fk_enderecos_obreiros1_idx` (`obreiro_end_fk` ASC),
  CONSTRAINT `fk_enderecos_obreiros1`
    FOREIGN KEY (`obreiro_end_fk`)
    REFERENCES `ijemavi`.`obreiros` (`id_obreiros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ijemavi`.`galeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ijemavi`.`galeria` (
  `id_galeria` INT NOT NULL AUTO_INCREMENT,
  `imagen_galeria` VARCHAR(100) NOT NULL,
  `nome_img_galeria` VARCHAR(100) NOT NULL,
  `obreiro_gal_fk` INT NOT NULL,
  PRIMARY KEY (`id_galeria`),
  INDEX `fk_galeria_obreiros1_idx` (`obreiro_gal_fk` ASC),
  CONSTRAINT `fk_galeria_obreiros1`
    FOREIGN KEY (`obreiro_gal_fk`)
    REFERENCES `ijemavi`.`obreiros` (`id_obreiros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ijemavi`.`dia_culto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ijemavi`.`dia_culto` (
  `id_dia_culto` INT NOT NULL AUTO_INCREMENT,
  `dia_semana_culto` VARCHAR(45) NOT NULL,
  `nome_culto` VARCHAR(100) NOT NULL,
  `hora_culto` VARCHAR(45) NOT NULL,
  `obreiro_diaculto_fk` INT NOT NULL,
  PRIMARY KEY (`id_dia_culto`),
  INDEX `fk_dia_culto_obreiros1_idx` (`obreiro_diaculto_fk` ASC),
  CONSTRAINT `fk_dia_culto_obreiros1`
    FOREIGN KEY (`obreiro_diaculto_fk`)
    REFERENCES `ijemavi`.`obreiros` (`id_obreiros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ijemavi`.`devocional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ijemavi`.`devocional` (
  `id_devocional` INT NOT NULL AUTO_INCREMENT,
  `data_dev` DATE NOT NULL,
  `titulo_dev` VARCHAR(45) NOT NULL,
  `descricao_dev` VARCHAR(45) NOT NULL,
  `foto_dev` VARCHAR(45) NULL,
  `autor_dev` VARCHAR(45) NOT NULL,
  `obreiro_dev_fk` INT NOT NULL,
  PRIMARY KEY (`id_devocional`),
  INDEX `fk_devocional_obreiros1_idx` (`obreiro_dev_fk` ASC),
  CONSTRAINT `fk_devocional_obreiros1`
    FOREIGN KEY (`obreiro_dev_fk`)
    REFERENCES `ijemavi`.`obreiros` (`id_obreiros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
